<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ABOUT' => 'Մեր մասին',

    'VISION' => 'ՏԵՍԼԱԿԱՆ',
    '-- Select Category --' => 'Ընտրել բաժինը',
    '-- Select City --' => 'Ընտրել քաղաքը',
    '-- Select Country --' => 'Ընտրել երկիրը',
    '-- Select Region --' => 'Ընտրել մարզը',
    '--- Select City ---' => 'Ընտրել քաղաքը',
    '-- Choose city --' => 'Ընտրել քաղաքը',
    'ABOUT US' => 'Մեր մասին',
    'CAREERS' => 'Աշխատանք',
    'CONTACT US' => 'Կապ',

    'Email' => 'Էլ․ հասցե',

    '--- Select Region ---' => 'Ընտրեք մարզը',

    'Thanks' => 'Շնորհակալություն',


    'is required' => ' պարտադիր է',
    'Required field' => 'Պարտադիր դաշտ',
    'State' => 'Մարզ',
    'City' => 'Քաղաք',
    'Select State' => 'Ընտրեք մարզը',
    'Gyumri' => 'Գյումրի',
    'Lori' => 'Լոռի',
    'Vanadzor' => 'Վանաձոր',
    'Shirak' => 'Շիրակ',
    'Applicants' => 'Դիմորդ',
    'Employed' => 'Աշխատում են',
    'Target benefits' => 'Թիրախ',

//    'CONTACT US' => 'Հետադարձ Կապ',
    'CONTACT INFO' => 'Կոնտակտային տվյալներ',

    'Republic of Armenia, Shirak' => 'Հայաստանի Հանրապետություն, Շիրակ',

    'Subjects and their duration can be downloaded from' => 'Առարկայացանկը և դրանց տևողությունը կարող եք բեռնել',
    'here.' => 'այստեղից:',
    'News & Events' => 'Նորություններ և իրադարձություններ',
    'Home' => 'Գլխավոր',

    'search' => 'որոնում',
    'hy' => 'Հայ',
    'ru' => 'рус',
    'en' => 'Eng',
    'de' => 'De',
    'fr' => 'Fr',


];
